### ISSUE TITLE
Blank Threshold Bug

### ISSUE THREAD

**Issue by sjyk** [sjyk/sampleclean-async#68]
When edit distance is used the user may specify a blank threshold.

**Comment by thisisdhaas** [comment]
Do we want to allow blank thresholds when 'autotune' is selected? thisisdhaas/wisteria-demo-interface@2b41596 does full validation, enforcing positive integer values for edit distance and floats in [0, 1] for the other similarity functions regardless of whether autotune is selected.

@sjyk Close this if that's the desired behavior, otherwise it's easy to allow blank values when autotune is selected.

**Comment by thisisdhaas** [comment]
thisisdhaas/wisteria-demo-interface@d444cf6 adds a dummy value for threshold under the hood when autotune is selected, producing the desired behavior
